"""Initial booking migration

Revision ID: 50220142ea1c
Revises: 
Create Date: 2026-08-16 19:26:42.460496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50220142ea1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema='reservas') as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_evento_fecha_apartado'))
        batch_op.create_index(batch_op.f('ix_reservas_evento_fecha'), ['fecha'], unique=False)
        batch_op.create_foreign_key(None, 'peticion', ['id_peticion'], ['id_peticion'], referent_schema='reservas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema='reservas') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reservas_evento_fecha'))
        batch_op.create_index(batch_op.f('ix_reservas_evento_fecha_apartado'), ['fecha'], unique=False)

    # ### end Alembic commands ###
