"""initial_schema

Revision ID: a4c8d96de67e
Revises: 
Create Date: 2026-08-16 22:18:41.100185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4c8d96de67e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'evento' in inspector.get_table_names(schema='reservas'):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id_evento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('id_salon', sa.Integer(), nullable=False),
    sa.Column('numero_alumnos', sa.Integer(), nullable=True),
    sa.Column('id_tipo_evento', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_peticion', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_peticion'], ['reservas.peticion.id_peticion'], ),
    sa.ForeignKeyConstraint(['id_tipo_evento'], ['reservas.tipo_evento.id_tipo_evento'], ),
    sa.PrimaryKeyConstraint('id_evento'),
    schema='reservas'
    )
    with op.batch_alter_table('evento', schema='reservas') as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_evento_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_evento_id_salon'), ['id_salon'], unique=False)

    op.create_table('peticion',
    sa.Column('id_peticion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_responsable', sa.Integer(), nullable=False),
    sa.Column('id_salon', sa.Integer(), nullable=False),
    sa.Column('id_programa', sa.Integer(), nullable=True),
    sa.Column('materia_nombre', sa.String(length=150), nullable=True),
    sa.Column('numero_alumnos', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('id_tipo_evento', sa.Integer(), nullable=False),
    sa.Column('prioridad_calculada', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['reservas.evento.id_evento'], ),
    sa.ForeignKeyConstraint(['id_tipo_evento'], ['reservas.tipo_evento.id_tipo_evento'], ),
    sa.PrimaryKeyConstraint('id_peticion'),
    schema='reservas'
    )
    with op.batch_alter_table('peticion', schema='reservas') as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_peticion_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_peticion_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_peticion_id_salon'), ['id_salon'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_peticion_id_usuario'), ['id_usuario'], unique=False)

    op.create_table('tipo_evento',
    sa.Column('id_tipo_evento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('peso_evento', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_evento'),
    schema='reservas'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('rol', postgresql.ENUM('COORDINADOR', 'ADMIN_PLANTEL', 'DOCENTE', 'ALUMNO', name='rolusuario'), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id_plantel_asignado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('usuarios_pkey'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    op.drop_table('tipo_evento', schema='reservas')
    with op.batch_alter_table('peticion', schema='reservas') as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_peticion_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_reservas_peticion_id_salon'))
        batch_op.drop_index(batch_op.f('ix_reservas_peticion_fecha'))
        batch_op.drop_index(batch_op.f('ix_reservas_peticion_estado'))

    op.drop_table('peticion', schema='reservas')
    with op.batch_alter_table('evento', schema='reservas') as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_evento_id_salon'))
        batch_op.drop_index(batch_op.f('ix_reservas_evento_fecha'))

    op.drop_table('evento', schema='reservas')
    # ### end Alembic commands ###
